FROM node:slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    wget \
    openssl \
    && rm -rf /var/lib/apt/lists/*

COPY package*.json ./
COPY prisma ./prisma

RUN npm install

COPY . .

EXPOSE 3000
EXPOSE 9229

CMD ["sh", "-c", "./scripts/db-deploy-with-reset.sh && npm run dev"]
