FROM node:slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    ffmpeg \
    curl \
    && rm -rf /var/lib/apt/lists/* \
    && apt-get clean

COPY package*.json ./

RUN npm install && npm cache clean --force

COPY . .

EXPOSE 3002

CMD ["node", "--watch", "src/index.js"]